### ISSUE TITLE
lolicon非r18源中也混入了少数r18的图片

### ISSUE THREAD

**Issue by rishenshun** [pcrbot/setu_renew#18]
插件版本：20210317下载的
问题描述：全局设置 config.json 中的 "lolicon_r18" 与 "r18" 均为 false ，但搜索一些普通关键字还是容易出r18的涩图，请问能否做限制？

**Comment by corvo007** [comment]
这个是因为图源里面非r18的也有一点点r18的，我之前也遇到过，后期会考虑再从tag中再筛选一遍
