### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by JMFANS** [pcrbot/setu_renew#21]
一个是lolicon负载均衡，我填入两个xxx,xxx的格式，显示api或被封禁？
一个是acggov的网址和api，网址打不开，api也找不到🌚🌚

**Comment by corvo007** [comment]
1.原网站是不支持、不鼓励多key单ip的，并且提到了滥用有可能被封禁
2.可能是你自己网络不好，我是能正常访问的

**Comment by as6296463** [comment]
> 1.原网站是不支持、不鼓励多key单ip的，并且提到了滥用有可能被封禁
> 2.可能是你自己网络不好，我是能正常访问的

你好，acggov的api是修改过吗？直接改setu_renew目前使用不了，Lolicon可以正常使用。

**Comment by corvo007** [comment]
> > 1.原网站是不支持、不鼓励多key单ip的，并且提到了滥用有可能被封禁
> > 2.可能是你自己网络不好，我是能正常访问的
> 
> 你好，acggov的api是修改过吗？直接改setu_renew目前使用不了，Lolicon可以正常使用。

请单开issue附上错误日志，然后我再排查
