### ISSUE TITLE
关于关键字搜索和图片缓存的问题

### ISSUE THREAD

**Issue by as6296463** [pcrbot/setu_renew#27]
今早使用关键字搜索涩图，一直显示搜索中，去服务器看发现报错提示“今日调用额度用完”，去群里了解说是每10分钟的自动缓存的调用也算进里面的次数。但是我手动输入setu 缓存时，Lolicon和acggov可以正常缓存图片，Lolicon_r18就也是报同样的调用额度用完错误，重复还是这样，Lolicon.py里的generate_image_struct中的r18也改成True了。然后关键字搜索的问题，我在群里和群友重复试验了，即使之前报过调用额度上限，还是能够成功搜索30张下载下来发图在群，但是有时就依然会报出同样的错误，就是一时成功一时又失败的那种。。。图1是图片缓存的报错，图2是关键字搜索的报错。
![QQ截图20210601153047](https://user-images.githubusercontent.com/37761817/120289695-2300dd00-c2f4-11eb-9e3a-15c2cd13b101.png)
![QQ截图20210601155949](https://user-images.githubusercontent.com/37761817/120289708-272cfa80-c2f4-11eb-829e-e4e75338a85a.png)

**Comment by corvo007** [comment]
那我估计这个api不仅有使用额度限制，还有频率限制。可能你之前缓存或者搜索太快了然后就导致服务器返回429，此时并非额度用完了

**Comment by as6296463** [comment]
> 那我估计这个api不仅有使用额度限制，还有频率限制。可能你之前缓存或者搜索太快了然后就导致服务器返回429，此时并非额度用完了

好的，谢谢解答。
