### ISSUE TITLE
修改max_pic_once_send参数无效果

### ISSUE THREAD

**Issue by tang-guo-guo** [pcrbot/setu_renew#3]
![Screenshot_2020-12-21-02-20-37-949_com microsoft rdc android](https://user-images.githubusercontent.com/71223830/102721084-79c0be80-4333-11eb-812d-72942d703ce3.jpg)
![Screenshot_2020-12-21-02-20-29-636_com tencent mobileqq](https://user-images.githubusercontent.com/71223830/102721087-7b8a8200-4333-11eb-9925-a4b1b06a4bd2.jpg)

**Comment by Katou-Kouseki** [comment]
同样遇到这个问题了
