### ISSUE TITLE
Lolicon的setu关键字搜索和acggov模块问题

### ISSUE THREAD

**Issue by as6296463** [pcrbot/setu_renew#30]
最近acggov模块使用不了，以前是正常能用的，后来发现去他的网站看发现图片都显示不了，以前在api直接访问调用案例能够返回一些参数，现在都没有了，是不是acggov他那边的api问题？它的setu缓存和关键字搜索、排行榜都用不了。
然后在使用Lolicon的功能时，发现关键字搜索图片总是在本地仓库中找了发出来，同一关键字搜出来的图片来来去去是同几张，不会像acggov那样从网上查找后下载发到群上，无论是在线（使用本地仓库）还是在线（不使用本地仓库），使用指令观察控制台还是没有在网上搜索的过程，但是我看代码里有写到网络搜索的部分，所以想来问下是我这边的问题还是代码哪里出错了。
![1](https://user-images.githubusercontent.com/37761817/121145856-f27bee80-c871-11eb-8b58-93f5473644db.png)
![2](https://user-images.githubusercontent.com/37761817/121145872-f576df00-c871-11eb-9c92-19f1ba148bdf.png)
![3](https://user-images.githubusercontent.com/37761817/121145875-f7d93900-c871-11eb-8e33-f7293f232894.png)
![4](https://user-images.githubusercontent.com/37761817/121145890-fb6cc000-c871-11eb-926a-d52a2dd8e3c9.png)
![5](https://user-images.githubusercontent.com/37761817/121145903-fdcf1a00-c871-11eb-99f8-a4492fd49e88.png)

输入后会直接输出没有符合条件的：
![6](https://user-images.githubusercontent.com/37761817/121146491-8fd72280-c872-11eb-8126-fbe9d01f7dde.png)
![7](https://user-images.githubusercontent.com/37761817/121146505-92d21300-c872-11eb-8183-2cc8fd01b755.jpg)

**Comment by corvo007** [comment]
猜测是网络问题导致搜索超时

**Comment by RayXu14** [comment]
我是自己改了代码，强制等待从网络上加载图片。我没有看得特别细，好像我们进行请求的时候，并不是从网上直接搜一张，而是从本地给出一张，然后网上搜索一张。当然这也可能只是网速太慢的运行路线，也许网速快就直接给网络搜索结果了，再次声明一下我没有特别细看代码

**Comment by RayXu14** [comment]
我是自己改了代码，强制等待从网络上加载图片。我没有看得特别细，好像我们进行请求的时候，并不是从网上直接搜一张，而是从本地给出一张，然后网上搜索一张缓存到本地。当然这也可能只是网速太慢的运行路线，也许网速快就直接给网络搜索结果了，再次声明一下我没有特别细看代码

**Comment by as6296463** [comment]
> 我是自己改了代码，强制等待从网络上加载图片。我没有看得特别细，好像我们进行请求的时候，并不是从网上直接搜一张，而是从本地给出一张，然后网上搜索一张缓存到本地。当然这也可能只是网速太慢的运行路线，也许网速快就直接给网络搜索结果了，再次声明一下我没有特别细看代码

没事，我也因为时间关系没有空去看和改，只能报下问题了
