### ISSUE TITLE
无法使用，无论怎么更改服务名都提示 Service name "涩图" already exist!

### ISSUE THREAD

**Issue by DavidYin166** [pcrbot/setu_renew#31]
File "/root/pcrbot/XCW/xcw/modules/setu_renew/__init__.py", line 16, in <module>
    sv = hoshino.Service('涩图', bundle='pcr娱乐', help_=HELP_MSG)
  File "/root/pcrbot/XCW/xcw/service.py", line 127, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "涩图" already exist!

报错显示服务名冲突了，但是我在__init__.py里的相关16行将“涩图”改成任何其他字符   都会提示一样的Service name "XXX" already exist! 然后导致涩图模块不工作。

**Comment by corvo007** [comment]
请检查是否还有其他涩图插件

**Comment by DavidYin166** [comment]
> 请检查是否还有其他涩图插件

多谢回复！检查了，其他的色图插件全删干净了。甚至用ide全文搜索都找不到有关联的代码了。

**Comment by DavidYin166** [comment]
> 请检查是否还有其他涩图插件

那个，就是，这个问题并不是服务名冲突，而是无论修改成什么服务名，都提示冲突。
如果只是服务名冲突，我就不会专门来提交issue了。

**Comment by corvo007** [comment]
> > 请检查是否还有其他涩图插件
> 
> 多谢回复！检查了，其他的色图插件全删干净了。甚至用ide全文搜索都找不到有关联的代码了。

那么只有这一个涩图插件的情况下还有这个问题吗

**Comment by DavidYin166** [comment]
> > > 请检查是否还有其他涩图插件
> > 
> > 
> > 多谢回复！检查了，其他的色图插件全删干净了。甚至用ide全文搜索都找不到有关联的代码了。
> 
> 那么只有这一个涩图插件的情况下还有这个问题吗

是的，是这样没错

**Comment by DavidYin166** [comment]
> > > 请检查是否还有其他涩图插件
> > 
> > 
> > 多谢回复！检查了，其他的色图插件全删干净了。甚至用ide全文搜索都找不到有关联的代码了。
> 
> 那么只有这一个涩图插件的情况下还有这个问题吗

是的，只有这一个涩图插件的情况下仍然有这个问题。
