### ISSUE TITLE
setu报错，和acg的排行榜获取失败，旧版可以。

### ISSUE THREAD

**Issue by zhtyirg3** [pcrbot/setu_renew#34]
![image](https://user-images.githubusercontent.com/55908974/126922125-b07b1868-a2bf-48ee-99da-16efdacb322c.png)
涩图能发出来，但是后台报错。
撤回失败了。
![98 J}@`{C)TM@9FZI782YK4](https://user-images.githubusercontent.com/55908974/127088017-95250c85-4880-42c8-93fd-fe763dd7e7e4.png)
![1](https://user-images.githubusercontent.com/55908974/127088121-0a4be757-3d57-4d6e-8988-8de5c23e2bf0.png)
还有ACG的排行榜使用不了，旧版的SETU MIX可以。
服务器是国外的。
请问大佬该如何解决？
![image](https://user-images.githubusercontent.com/55908974/126923146-74dc7528-ca30-46ab-afec-2529ce905bee.png)
对了还有一个，搜索功能好像比之前差了一点意思。
图会重复，好像不会在线搜，只会在仓库里挑选。

**Comment by zhtyirg3** [comment]
对了还有一个，搜索功能好像比之前差了一点意思。
图会重复，关键字必须得准确。

**Comment by corvo007** [comment]
看execption是服务器断开连接，估计是本地网络问题，建议使用代理。
另外，lolicon上特定tag只有几张甚至一张图片，所以这些tag肯定会出现重复的情况。
