### ISSUE TITLE
大佬，请问代理设置中可以设置成本地梯子的代理端口吗

### ISSUE THREAD

**Issue by AndoKaguya** [pcrbot/setu_renew#39]
如题，
比如开了梯子，可否设置成代理为 http://127.0.0.1:8080/ 或者 socks5://127.0.0.1:8080/ 这样呢？
还是说配置中的代理设置只能设置类似于 pixivcat 那种无墙的镜像站？

**Comment by corvo007** [comment]
`pixiv_proxy`是访问pixiv的镜像站地址，并非本地代理；
`lolicon_proxy` 是本地代理，只支持http代理

**Comment by AndoKaguya** [comment]
> `pixiv_proxy`是访问pixiv的镜像站地址，并非本地代理；
> `lolicon_proxy` 是本地代理，只支持http代理

谢谢大佬指点！
