### ISSUE TITLE
直连pixiv错误

### ISSUE THREAD

**Issue by UVJkiNTQ** [pcrbot/setu_renew#51]
https://github.com/pcrbot/setu_renew/commit/0486dd6a73975e956df1503f112dc6083f28ff9f#diff-f4b310389846f1edc33496efe59c52fc4c7633efa0ec965d41d044ac0755034bR94

选项为直连时报错

可能这条更改应作用于代理用户，但错误作用于了直连？

**Comment by UVJkiNTQ** [comment]
[2022-01-16 13:31:45,815 涩图] ERROR: replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/__init__.py", line 285, in send_search_setu
    msg = await get_setu(gid)
  File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/base.py", line 80, in get_setu
    image = await lolicon_get_setu(1)
  File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 273, in lolicon_get_setu
    image_list = await get_setu_online(1, r18)
  File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 169, in get_setu_online
    image_list = await query_setu(r18=r18, keyword=keyword)
  File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 94, in query_setu
                                                                                                 image['url'] = item['urls']['regular' if thumb else 'original'].replace("https://i.pixiv.cat/",
TypeError: replace() argument 2 must be str, not None

**Comment by corvo007** [comment]
近期会重构项目，因此现有的老版本就不再做更新和维护。

**Comment by soapspree** [comment]
> [2022-01-16 13:31:45,815 涩图] ERROR: replace() argument 2 must be str, not None Traceback (most recent call last): File "/root/qqbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message await service_func.func(bot, event) File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/**init**.py", line 285, in send_search_setu msg = await get_setu(gid) File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/base.py", line 80, in get_setu image = await lolicon_get_setu(1) File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 273, in lolicon_get_setu image_list = await get_setu_online(1, r18) File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 169, in get_setu_online image_list = await query_setu(r18=r18, keyword=keyword) File "/root/qqbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 94, in query_setu image['url'] = item['urls']['regular' if thumb else 'original'].replace("https://i.pixiv.cat/", TypeError: replace() argument 2 must be str, not None

我测试了一下，没有复现这个问题，配置文件如下：

    "pixiv_direct": true,
    "proxy_site": "",
    "local_proxy": ""

推测是因为配置文件有错误，导致`config.py`中的`get_config`函数读取不到对应值而返回None，`proxy_site`配置为`""`是没问题的，不会获取为NoneType。因此程序本身应该是没有问题的，你可以尝试重新替换一份配置文件或者重新克隆仓库，如果还是不行那就只能麻烦等下作者重构了。。。

**Comment by UVJkiNTQ** [comment]
是template变化没更新，少了local的项目
