### ISSUE TITLE
匹配正则是否可以优化一下

### ISSUE THREAD

**Issue by fuchenhqh** [pcrbot/setu_renew#6]
你好，就是有时候出于习惯（虽然可以直接”瑟图“），想直接“来张瑟图”，结果不触发。
然后看了一下源码"(?P<num>\d+)"，必须要匹配到一位数字才行，改成"*"感觉也不错23333。

**Comment by corvo007** [comment]
emmmm之前是(.*)后来反馈说只能识别一位数，然后就改了，那我改回去吧
